# Generated by Django 5.0.6 on 2024-07-15 22:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(default='static/services/default.png', upload_to="static/image/", verbose_name='Ссылка')),
                ('alt', models.CharField(max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заведения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Информация о заведении')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес заведения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заведению')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно/неактивно')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_photo', to='product.image', verbose_name='Фото заведения')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Информация о блюде')),
                ('count', models.IntegerField(default=1, verbose_name='Количество блюд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена блюда')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к блюду')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно/неактивно')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='product.establishment')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_photo', to='product.image', verbose_name='Фото блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка на услугу')),
                ('dateFrom', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала акции')),
                ('dateTo', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно/неактивно')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_photo', to='product.image', verbose_name='Фото услуги')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно/неактивно')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название букета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Информация о букете')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Количество цветов в букете')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена букета')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к букету')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно/неактивно')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers_photo', to='product.image', verbose_name='Фото букета')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='product.service')),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='product.service'),
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_address', models.CharField(max_length=255, verbose_name='Адрес посадки пассажира')),
                ('dropoff_address', models.CharField(max_length=255, verbose_name='Адрес высадки пассажира')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время для подачи такси')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена такси')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к такси')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно/неактивно')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxis', to='product.service')),
            ],
            options={
                'verbose_name': 'Такси',
                'verbose_name_plural': 'Такси',
            },
        ),
    ]
