# Generated by Django 5.0.6 on 2024-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AddField(
            model_name='establishment',
            name='closing_time',
            field=models.TimeField(default='22:00', verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='opening_time',
            field=models.TimeField(default='10:00', verbose_name='Время открытия'),
        ),
    ]
