# Generated by Django 5.0.6 on 2024-07-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_src_alter_taxi_price_decoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена оформления'),
        ),
    ]
