# Generated by Django 5.0.6 on 2024-11-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_reservation_options_establishment_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='end_date',
        ),
    ]
