# Generated by Django 5.0.6 on 2024-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_establishment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='start_date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
    ]
