# Generated by Django 5.0.6 on 2024-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_decoration_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к оформлению'),
        ),
    ]
