# Generated by Django 5.0.6 on 2024-09-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
