# Generated by Django 5.0.6 on 2024-09-01 19:29

import user_account_auth.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_auth', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_account_auth.managers.UserManager()),
            ],
        ),
    ]
